# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
    api_key = app_store_connect_api_key(
    key_id: "DZ2AGVFRXS",
    issuer_id: "69a6de97-1b94-47e3-e053-5b8c7c11a4d1",
    key_filepath: "~/AuthKey_DZ2AGVFRXS.p8",
    duration: 1200, # optional (maximum 1200)
    in_house: false # optional but may be required if using match/sigh
  )

platform :ios do
  desc "Push a new beta build to TestFlight"
  
  lane :beta do
    pilot(api_key: api_key)
    increment_build_number(xcodeproj: "iSpend.xcodeproj")
    build_app(scheme: "iSpend")
    upload_to_testflight
  end
end

lane :release do
  capture_screenshots
  build_app
  upload_to_app_store       # Upload the screenshots and the binary to iTunes
end

lane  :bump do
        increment_build_number(xcodeproj: "iSpend.xcodeproj")
end

