# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  
  lane :beta do
    # Define API key for this lane
    api_key = app_store_connect_api_key(
      key_id: "FT7L9OTKI7J1",
      issuer_id: "69a6de97-1b94-47e3-e053-5b8c7c11a4d1",
      key_filepath: File.expand_path("~/AuthKey_FT7L9OTKI7J1.p8"),
      duration: 1200,
      in_house: false
    )
    
    increment_build_number(xcodeproj: "iSpend.xcodeproj")
    
    # Build and export IPA
    gym(
      scheme: "iSpend",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "iSpend",
      clean: true
    )
    
    upload_to_testflight(
      api_key: api_key,
      ipa: "./build/iSpend.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end

lane :release do
  capture_screenshots
  build_app
  upload_to_app_store       # Upload the screenshots and the binary to iTunes
end

lane  :bump do
        increment_build_number(xcodeproj: "iSpend.xcodeproj")
end

lane :upload do
  # Define API key for upload
  api_key = app_store_connect_api_key(
    key_id: "FT7L9OTKI7J1",
    issuer_id: "69a6de97-1b94-47e3-e053-5b8c7c11a4d1",
    key_filepath: File.expand_path("~/AuthKey_FT7L9OTKI7J1.p8"),
    duration: 1200,
    in_house: false
  )
  
  upload_to_testflight(
    api_key: api_key,
    ipa: "./build/iSpend.ipa",
    skip_waiting_for_build_processing: true
  )
end

